export { FiscalCodeAssistField, AddressCapAssistFields } from './AnagraficaAssistFields'
export { default as CodiceFiscalePopup } from './CodiceFiscalePopup'
export { default as CapLookupPopup } from './CapLookupPopup'
export { default as VatNumberAssistField } from './VatNumberAssistField'
export type { VatResolvedData } from './VatNumberAssistField'
